PATH := /usr/um/gcc-4.7.0/bin:$(PATH)
LD_LIBRARY_PATH := /usr/um/gcc-4.7.0/lib64
LD_RUN_PATH := /usr/um/gcc-4.7.0/lib64

eecs485pa5p:
	g++ -g pageRank.cpp -std=c++11 -o pageRank
clean:
	rm -f pageRank *.o
