PATH := /usr/um/gcc-4.7.0/bin:$(PATH)
LD_LIBRARY_PATH := /usr/um/gcc-4.7.0/lib64
LD_RUN_PATH := /usr/um/gcc-4.7.0/lib64

eecs485pa5p:
	g++ hits.cpp -std=c++11 -o eecs485pa5h
clean:
	rm -f eecs485pa5h *.o
